# Docker image deployed to silverbullet.md
ARG BASE_IMAGE=zefhemel/silverbullet:v2
FROM ${BASE_IMAGE}

ENV SB_INDEX_PAGE=SilverBullet
ENV SB_READ_ONLY=1

ADD docs /space

ADD https://github.com/MrMugame/silversearch/releases/download/edge/silversearch.plug.js /space/
